Update build-and-deploy.yml

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -21,18 +21,15 @@ jobs:
       - name: Install JavaScript dependencies
         run: npm install
 
-      - name: Generate Podfile.lock (and ignore failure)
+      - name: Install CocoaPods (with boost checksum fix)
         working-directory: ./ios
-        run: pod install
-        continue-on-error: true
-
-      - name: Correct boost checksum in Podfile.lock
-        working-directory: ./ios
-        run: sed -i '' 's/f0397ba6e982c4450f27bf32a2a83292aba035b827a5623a14636ea583318c41/9c2f4b99bc7ddb95a8babff8ba78a4108aa0951243ea919166a7e2e279825502/g' Podfile.lock
-
-      - name: Install CocoaPods with corrected lockfile
-        working-directory: ./ios
-        run: pod install
+        run: |
+          pod install || ( \
+            echo "Initial pod install failed. Applying boost checksum fix..." && \
+            sed -i '' 's/f0397ba6e982c4450f27bf32a2a83292aba035b827a5623a14636ea583318c41/9c2f4b99bc7ddb95a8babff8ba78a4108aa0951243ea919166a7e2e279825502/g' Podfile.lock && \
+            echo "Checksum fixed. Retrying pod install..." && \
+            pod install \
+          )
 
       - name: Upload to TestFlight
         uses: apple-actions/upload-testflight-build@v2
